on:
  # release:
  #   types: 
  #     - created
  workflow_dispatch:
    inputs: {}

jobs:
  release-build:
    name: Release ${{ matrix.build }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        fail-fast: false
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: kameloso

          - build: linux
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            binary_name: kameloso

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            binary_name: kameloso.exe
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Install musl-tools
        if: ${{ endsWith(matrix.target,'musl') }}
        run: sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create archive folder
        run: mkdir kameloso

      - name: Copy artifact
        run: cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} kameloso/

      - name: Copy public folder
        run: cp -r public kameloso/public

      - name: Create archive
        run: cd release && zip -r kameloso-${{ matrix.target }}.zip kameloso

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: kameloso-${{ matrix.target }}
          path: kameloso-${{ matrix.target }}.zip
