name: Test/lint

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"

jobs:
  test-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: cargo check
        run: cargo check --target ${{ matrix.target }}

      - name: cargo test
        run: cargo test --target ${{ matrix.target }}

      - name: cargo clippy
        run: cargo clippy

      - name: cargo fmt
        run: cargo fmt --check
